_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "swin_tiny_patch4_window7_224_d2.pth"
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  BACKBONE:
    NAME: "build_swint_fpn_backbone"
  SWINT:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
INPUT:
  FORMAT: "RGB"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  WEIGHT_DECAY: 0.05
  BASE_LR: 0.0001
  AMP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 10000 

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)

OUTPUT_DIR: "./output_swin_t_3x"
